language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

before_script:
  - composer self-update
  - composer install

script:
  - phpunit
